[tox]
envlist =
    tests
    linting
    coverage
    type_check
skip_missing_interpreters = True
skipsdist = True

[testenv]
commands = python -m pip install --upgrade pip

[testenv:tests]
deps =
    .[tests]
setenv = PYTHONPATH = {toxinidir}/src
commands = python -m pytest unittests --basetemp={envtmpdir} {posargs}

[testenv:linting]
deps =
    {[testenv:tests]deps}
    .[linting]
setenv = PYTHONPATH = {toxinidir}/src
commands =
    pylint sap_mcp_config
    pylint unittests --rcfile=unittests/.pylintrc

[testenv:type_check]
setenv = PYTHONPATH = {toxinidir}/src
deps =
    {[testenv:tests]deps}
    .[type_check]
commands =
    mypy --show-error-codes src/sap_mcp_config --strict
    mypy --show-error-codes unittests --strict

[testenv:spell_check]
setenv = PYTHONPATH = {toxinidir}/src
deps =
    .[spell_check]
commands =
    codespell --ignore-words=domain-specific-terms.txt src
    codespell --ignore-words=domain-specific-terms.txt README.md

[testenv:coverage]
changedir = {toxinidir}
deps =
    {[testenv:tests]deps}
    .[coverage]
setenv = PYTHONPATH = {toxinidir}/src
commands =
    coverage run -m pytest unittests --basetemp={envtmpdir} {posargs}
    coverage html --omit .tox/*,unittests/*
    coverage report --fail-under 80 --omit .tox/*,unittests/*

[testenv:test_packaging]
skip_install = true
deps =
    .[packaging]
commands =
    python -m build
    twine check dist/*
